blank_issues_enabled: true
contact_links:
 - name: General Question
    url: https://github.com/Pro7ech/lattigo/discussions
    about: Ask a question that is not necessarily related to the use or implementation of the library.
